### PR TITLE
Add Time-Dependent Point Source Tutorial

### PR DESCRIPTION
**Pull request by wmwv**
Adds a working Tutorial extract supernovae lightcurves from simulated Rubin (DESC DC2) and Roman images.

Cons:
* It's a bit long.
* Data download requirements are large (many GBs).
* Still need to add WCS/SIP to AstroPhot.  Would be good to remove per-epoch astrometric fits, for reasons of speed, correctness, and simplicity.

Pros:
* It's very close to a science use case that people will really care about.
* It's use simulated data that people will care about for Roman and Rubin.
* It shows the case for an object that is in some images but not others.
* It shows reading in a PSF from images (Rubin) or models (Roman) and using those in the photometry.

### CODE REVIEW

**Comment by wmwv** [comment]
@ConnorStoneAstro What do you think?
1. Does this run for you?
2. Is this a reasonable scope for a tutorial.  I fear it's a bit much.
3. Do you have any suggestions for improvements for the tutorial?

**Comment by ConnorStoneAstro** [comment]
@wmwv this is so cool! I'll take a look at this as soon as I get a chance :)

**Comment by wmwv** [comment]
I've added rendered versions of the Notebooks for each of the three different example SN for ease of reference.  That leads to one more question:
4. Which SN should we save as rendered Notebook?

I'll remove these and rewrite the history once we resolve what we want to do.

**Comment by ConnorStoneAstro** [comment]
I'm working my way through the tutorial, this is super cool to see! One issue I ran into is that the script provided for downloading and extracting the Roman SN data doesn't quite work on the last line, I think it should look more like this:
```
cd data/RomanSN; for f in rotate_update_Y106_*.tar.gz; do tar -xvzf "$f" --wildcards --no-anchored '*_1.fits.gz'; done; gunzip *.fits.gz; gunzip *.FITS.gz; rm *.tar.gz; cd -
```

I am now down to cell 30 where the PSF_Star_Linear is created. It looks like this is from before the PSF update. Could you tell me which version of AstroPhot I should use to run it?

**Comment by wmwv** [comment]
```
cd data/RomanSN; for f in rotate_update_Y106_*.tar.gz; do tar -xvzf "$f" --wildcards --no-anchored '*_1.fits.gz'; done; gunzip *.fits.gz; gunzip *.FITS.gz; rm *.tar.gz; cd -
```

Oh, right.  The extract structure of this command depends on what shell you're running (bash, tcsh, zsh, ...).

**Comment by wmwv** [comment]
This runs under v0.15.2 (which I should document).

What SHA are you reviewing?   The latest is`8d28c29`.

**Comment by wmwv** [comment]
There is a side branch, currently at `d2347ca`, `u/wmwv/psf_star_linear` where I was playing around with trying to fit in linear flux space (and was with respect to the earlier AstroPhot version before the PSF reworking).  But that's not in this PR.

**Comment by ConnorStoneAstro** [comment]
Ah, you're right! That's my bad. ok I'm going through the right one now :)

**Comment by ConnorStoneAstro** [comment]
Ok, I got the Roman SN notebook to run. This is really incredible!!! :) Thanks so much for putting this together!!!

One note, here is the bash script I needed in order for the data to download correctly:
```
DATADIR=data/RomanSN
mkdir -p ${DATADIR}
curl "https://roman.ipac.caltech.edu/data/sims/sn_image_sims/rotate_update_Y106_132.tar.gz" --output ${DATADIR}/rotate_update_Y106_132.tar.gz
curl "https://roman.ipac.caltech.edu/data/sims/sn_image_sims/rotate_update_Y106_160.tar.gz" --output ${DATADIR}/rotate_update_Y106_160.tar.gz
curl "https://roman.ipac.caltech.edu/data/sims/sn_image_sims/rotate_update_Y106_170.tar.gz" --output ${DATADIR}/rotate_update_Y106_170.tar.gz

# SN input catalog / SN
curl https://roman.ipac.caltech.edu/data/sims/sn_image_sims/WFIRST_AKARI_FIXED_HEAD.FITS --output ${DATADIR}/WFIRST_AKARI_FIXED_HEAD.FITS

# SN input lightcurves
curl https://roman.ipac.caltech.edu/data/sims/sn_image_sims/WFIRST_AKARI_FIXED_PHOT.FITS.gz --output ${DATADIR}/WFIRST_AKARI_FIXED_PHOT.FITS.gz

# SN truth
curl https://roman.ipac.caltech.edu/data/sims/sn_image_sims/rotate_Y_truth.tar.gz --output ${DATADIR}/rotate_Y_truth.tar.gz

# Image Metadata
curl https://roman.ipac.caltech.edu/data/sims/sn_image_sims/paper_rotate.fits --output ${DATADIR}/paper_rotate.fits

cd data/RomanSN;
for f in rotate_update_Y106_*.tar.gz;
    do tar -xvzf "$f" --wildcards --no-anchored '*_1.fits.gz';
    tar -xvzf "$f" --wildcards --no-anchored '*_10.fits.gz';
done;
gunzip *.fits.gz;
gunzip *.FITS.gz;
cd -
```

Otherwise, everything ran very smoothly. I found it challenging to understand some of the section around the covariance matrix. There is a little script you can run in that section:
```
covv = result.covariance_matrix.detach().cpu().numpy()
covv[np.abs(covv) > 1e4] = 1
fig, ax = ap.plots.covariance_matrix(
    covv,
    result.model.parameters.vector_values().detach().cpu().numpy(),
    result.model.parameters.vector_names(),
)
plt.show()
```
which will produce a corner plot to show the information in the covariance matrix. Interestingly there are some parameters where it looks like the covariance is super strong. Anyway, based on your comparisons with the ground truth it looked to me like it is in the right ballpark :)

I'm thrilled to see this working!!! :)

**Comment by wmwv** [comment]
I've updated the shell commands so they work whether you're calling, sourcing, or cutting-and-pasting the commands.

**Review by ConnorStoneAstro — APPROVED** [review]
These are absolutely incredible!!! Really amazing analysis and results :) 

I noticed that you were looking for the names of the elements in a covariance matrix. You can do model.parameters.vector_names() to get a vector of parameter names which matches the dimensionality of the covariance matrix and the other "vector" quantities. The drawback is that it is just the leaf name so it will have `q` or `n` but not the `model 1` or whatever named model owns the parameter. So in big models there's lots of duplicates

**Pull request merged**
